[project]
name = "id-discord-gotta-bike"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.*"
dependencies = [
    "httpx>=0.28.1",
    "logfire>=3.5.1",
    "py-cord>=2.6.1",
    "pydantic>=2.10.6",
    "pydantic-settings>=2.7.1",
    "python-dotenv>=1.0.1",
]
